### ISSUE TITLE
bug(kube-prometheus): argocd sync failing

### ISSUE THREAD

**Issue by shsingh** [apcj-f5/nap-devsecops-demo#325]
currently argocd sync is setup for kube-prometheus is failing as roles and other objects are already created.

replace=true does not seem to work for re-creating these as per:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/apcj-f5/nap-devsecops-demo.git
      targetRevision: deploy
      path: argocd/manifests/kube-prometheus
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - ServerSideApply=true
```

Errors like this are seen everytime kube-prometheus app is updated:

clusterroles.rbac.authorization.k8s.io "kube-prometheus-stack-admission" already exists
